# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request

on:
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: '14.0.2'
        architecture: x64
    - name: Build
      run: |
        gradlew.bat RatPoison
